#!/usr/bin/env python3
"""
update_macros.py — regenerate the measured-quantity macro block in
manuscript/main.tex from the analysis JSONs, so every number in the paper
has a single source of truth.
"""

import json
import os
import re

OUT = '/Users/ljm/Desktop/cyc/paper_v2'
TEX = os.path.join(OUT, 'manuscript', 'main.tex')

KEYMAP = {'J0005': 'aaa', 'J0022': 'bbb', 'J0749': 'ccc', 'J0035': 'ddd'}


def fmt(x, nd=1):
    return f'{x:.{nd}f}'


def load(src):
    p = os.path.join(OUT, 'data', f'{src}_joint_results.json')
    if not os.path.exists(p):
        return None
    with open(p) as f:
        return json.load(f)


def macro_block():
    lines = ['% === AUTO-GENERATED by code/update_macros.py — do not edit by hand ===']
    for src, suff in KEYMAP.items():
        r = load(src)
        if r is None:
            lines.append(f'% {src}: no results yet')
            continue
        post = r.get('posterior')
        sols = sorted(r['solutions'], key=lambda s: s['chi2'])
        p0 = sols[0]['p']
        if post and 'B_MG' in post:
            B = post['B_MG']['q50']
            Berr = 0.5 * (post['B_MG']['q84'] - post['B_MG']['q16'])
            kT = post['kT_keV']['q50']
            kTerr = 0.5 * (post['kT_keV']['q84'] - post['kT_keV']['q16'])
            th = post['theta_deg']['q50']
            therr = 0.5 * (post['theta_deg']['q84'] - post['theta_deg']['q16'])
            ll = post['log_Lambda']['q50']
            llerr = 0.5 * (post['log_Lambda']['q84'] - post['log_Lambda']['q16'])
        else:
            B, Berr = p0[3], float('nan')
            kT, kTerr = p0[4], float('nan')
            th, therr = p0[5], float('nan')
            ll, llerr = p0[6], float('nan')
        ndT = 2 if (kTerr < 0.1 or kT < 1.0) else 1
        ndB = 2 if Berr < 0.1 else 1
        lines += [
            f'\\newcommand{{\\BJ{suff}}}{{{fmt(B)}}}',
            f'\\newcommand{{\\BJ{suff}Err}}{{{fmt(Berr, ndB)}}}',
            f'\\newcommand{{\\TJ{suff}}}{{{fmt(kT, ndT)} \\pm {fmt(kTerr, ndT)}}}',
            f'\\newcommand{{\\thJ{suff}}}{{{fmt(th,0)} \\pm {fmt(therr,0)}}}',
            f'\\newcommand{{\\lamJ{suff}}}{{{fmt(ll)} \\pm {fmt(llerr)}}}',
            f'\\newcommand{{\\chiredJ{suff}}}{{{fmt(r["chi2_red"])}}}',
        ]
        alts = [s for s in sols[1:] if abs(s['p'][3] - B) > 3.0]
        if alts:
            alt_str = ', '.join(fmt(s['p'][3]) for s in alts)
            lines.append(f'\\newcommand{{\\BaltJ{suff}}}{{{alt_str}}}')
        else:
            lines.append(f'\\newcommand{{\\BaltJ{suff}}}{{--}}')
    lines.append('% --- timing (from *_lc_results.json) ---')
    for src, suff in KEYMAP.items():
        p = os.path.join(OUT, 'data', f'{src}_lc_results.json')
        if not os.path.exists(p):
            continue
        with open(p) as f:
            lc = json.load(f)
        pk = lc['combined_peak']
        lines.append(f'\\newcommand{{\\PJ{suff}}}{{{pk["P_min"]:.3f}}}')
    lines += physics_block()
    lines.append('% === END AUTO-GENERATED ===')
    return '\n'.join(lines)


# distances (pc) for the flux-calibrated DESI sources
DIST_PC = {'J0005': 604.0, 'J0022': 583.0, 'J0749': 946.0}
PC_CM = 3.0857e18
R_WD_CM = 7.0e8        # canonical 0.6 Msun WD radius
G_CGS = 6.674e-8
MSUN_G = 1.989e33
KEV_J = 1.602176634e-16


def physics_block():
    """Cyclotron luminosity, fractional emitting area, accretion-rate
    lower limit, and magnetic moment, from the adopted joint solutions."""
    import sys
    import numpy as np
    sys.path.insert(0, '/Users/ljm/Desktop/cyc/优化算法/m2_optimized')
    from cyclotron_m2 import cal_cy_spec
    lines = ['% --- accretion-region physics (computed here from the '
             'adopted solutions) ---']
    for src, suff in KEYMAP.items():
        if src not in DIST_PC:
            continue
        r = load(src)
        if r is None:
            continue
        sols = sorted(r['solutions'], key=lambda s: s['chi2'])
        adopted = next((s for s in sols if s.get('adopted')), sols[0])
        p = adopted['p']
        A_cyc = adopted['amps'][2]
        B, kT, th, logL = p[3], p[4], p[5], p[6]
        wav = np.linspace(3000e-10, 25000e-10, 600)
        spec = cal_cy_spec(wav, kT * KEV_J, B * 100.0, np.deg2rad(th),
                           10.0 ** logL)
        shape = spec / spec.max()
        Fcyc = np.trapz(A_cyc * shape, wav * 1e10)     # erg/s/cm2
        d = DIST_PC[src] * PC_CM
        Lcyc = 4.0 * np.pi * d * d * Fcyc
        # emitting area from the Rayleigh-Jeans peak intensity
        lam_pk_cm = wav[np.argmax(spec)] * 1e2
        T_K = kT * KEV_J / 1.381e-23
        I_RJ = 2 * 2.998e10 * 1.381e-16 * T_K / lam_pk_cm**4 / 1e8
        a_em = A_cyc * d * d / I_RJ
        f_area = a_em / (4 * np.pi * R_WD_CM**2)
        Mdot = Lcyc * R_WD_CM / (G_CGS * 0.6 * MSUN_G)
        Mdot_yr = Mdot * 3.156e7 / MSUN_G
        mu = B * 1e6 * R_WD_CM**3
        def sci(x, nd=1):
            ex = int(np.floor(np.log10(abs(x))))
            return f'{x/10**ex:.{nd}f} \\times 10^{{{ex}}}'
        lines += [
            f'\\newcommand{{\\LcycJ{suff}}}{{{sci(Lcyc)}}}',
            f'\\newcommand{{\\fareaJ{suff}}}{{{sci(f_area)}}}',
            f'\\newcommand{{\\MdotJ{suff}}}{{{sci(Mdot_yr)}}}',
            f'\\newcommand{{\\muJ{suff}}}{{{sci(mu)}}}',
        ]
    return lines


def main():
    with open(TEX) as f:
        tex = f.read()
    block = macro_block()
    pat = re.compile(
        r'% === AUTO-GENERATED.*?% === END AUTO-GENERATED ===',
        re.S)
    if pat.search(tex):
        tex = pat.sub(block.replace('\\', '\\\\'), tex, count=1)
        tex = tex.replace(block.replace('\\', '\\\\'), block)
    else:
        # replace the original hand-written macro section
        start = tex.index('% --- J0005+2941 ---')
        end = tex.index('\\begin{document}')
        tex = tex[:start] + block + '\n\n' + tex[end:]
    with open(TEX, 'w') as f:
        f.write(tex)
    print(block)
    print('\nmain.tex macro block updated.')


if __name__ == '__main__':
    main()
